"""language.py: 言語判定・test判定・generated判定・vague filename のテスト。"""
from __future__ import annotations

import unittest
from pathlib import Path

import _testutil  # noqa: F401

import language


class TestDetectLanguage(unittest.TestCase):
    def test_known_extensions(self):
        cases = {
            "foo.py": "python",
            "foo.js": "javascript",
            "foo.mjs": "javascript",
            "foo.cjs": "javascript",
            "foo.jsx": "javascriptreact",
            "foo.ts": "typescript",
            "foo.mts": "typescript",
            "foo.cts": "typescript",
            "foo.tsx": "typescriptreact",
            "Foo.java": "java",
            "Foo.cs": "csharp",
            "Foo.kt": "kotlin",
            "Foo.kts": "kotlin",
            "foo.dart": "dart",
            "foo.go": "go",
            "foo.rs": "rust",
            "foo.rb": "ruby",
            "foo.php": "php",
        }
        for name, expected in cases.items():
            with self.subTest(name=name):
                self.assertEqual(language.detect_language(Path(name)), expected)

    def test_unknown_extension_is_generic(self):
        self.assertEqual(language.detect_language(Path("foo.xyz")), "generic")
        self.assertEqual(language.detect_language(Path("Makefile")), "generic")

    def test_case_insensitive_extension(self):
        self.assertEqual(language.detect_language(Path("Foo.PY")), "python")


class TestIsTestPath(unittest.TestCase):
    def test_test_dir_markers(self):
        for dir_name in ("test", "tests", "__tests__", "spec", "specs", "e2e"):
            with self.subTest(dir_name=dir_name):
                self.assertTrue(language.is_test_path(Path(f"/repo/{dir_name}/foo.py")))

    def test_test_filename_markers(self):
        cases = [
            "test_foo.py",
            "foo_test.py",
            "foo.test.ts",
            "foo.test.tsx",
            "foo.spec.ts",
            "foo.spec.tsx",
            "FooTest.java",
            "foo_test.go",
        ]
        for name in cases:
            with self.subTest(name=name):
                self.assertTrue(language.is_test_path(Path(f"/repo/src/{name}")))

    def test_normal_path_not_test(self):
        self.assertFalse(language.is_test_path(Path("/repo/src/handler.py")))
        self.assertFalse(language.is_test_path(Path("/repo/src/service.ts")))

    def test_dir_marker_case_insensitive(self):
        self.assertTrue(language.is_test_path(Path("/repo/TESTS/foo.py")))


class TestIsGeneratedByContent(unittest.TestCase):
    def test_markers_within_first_five_lines(self):
        markers = [
            "// Code generated by protoc-gen-go. DO NOT EDIT.",
            "# @generated",
            "// This file was generated by a tool",
            "// auto-generated, do not modify",
        ]
        for marker in markers:
            with self.subTest(marker=marker):
                lines = ["", marker, "", "", ""]
                self.assertTrue(language.is_generated_by_content(lines))

    def test_marker_case_insensitive(self):
        self.assertTrue(language.is_generated_by_content(["DO NOT EDIT"]))

    def test_marker_outside_first_five_lines_not_detected(self):
        # 呼び出し側が lines[:5] を渡す想定だが、関数自身も内部で [:5] に絞る
        # (二重防御)。6 行目以降のマーカーは、素の (未スライス) リストを渡しても
        # 検出されないことを確認する。
        lines = ["1", "2", "3", "4", "5", "@generated"]
        self.assertFalse(language.is_generated_by_content(lines))

    def test_no_marker_returns_false(self):
        self.assertFalse(language.is_generated_by_content(["import os", "x = 1"]))


class TestIsVagueFilename(unittest.TestCase):
    def test_utils_py_is_vague(self):
        self.assertTrue(language.is_vague_filename(Path("/repo/utils.py")))

    def test_user_service_py_is_not_vague(self):
        self.assertFalse(language.is_vague_filename(Path("/repo/user_service.py")))

    def test_common_service_ts_is_vague(self):
        self.assertTrue(language.is_vague_filename(Path("/repo/CommonService.ts")))

    def test_index_ts_is_not_vague(self):
        self.assertFalse(language.is_vague_filename(Path("/repo/index.ts")))


if __name__ == "__main__":
    unittest.main()
