#!/usr/bin/env python3
"""純粋関数: 言語判定・test 判定・generated 判定・vague filename 判定。

ファイルシステムアクセスは行わない (source.py の責務)。
"""
from __future__ import annotations

import re
from pathlib import Path

# 判定対象の allowlist を兼ねる: ここに無い拡張子は `is_code_path` が False を
# 返し、__main__ が早期 skip する (0.2.0 以降)。Markdown / JSON / YAML / CSV /
# SQL 等の非コードファイルが行数だけで分割検討を促されるのを避けるため。
EXTENSION_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "javascriptreact",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "typescriptreact",
    ".java": "java",
    ".cs": "csharp",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".dart": "dart",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    # 以下は 0.2.0 で追加。allowlist 化する前は "generic" (係数 1.0) として
    # 判定されていた実コードであり、登録しないと判定対象から丸ごと外れる。
    ".swift": "swift",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hh": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".m": "objectivec",
    ".mm": "objectivec",
    ".scala": "scala",
    ".ex": "elixir",
    ".exs": "elixir",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".r": "r",
    ".vue": "vue",
    ".svelte": "svelte",
    ".groovy": "groovy",
    ".ps1": "powershell",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".hs": "haskell",
    ".erl": "erlang",
    ".jl": "julia",
    ".zig": "zig",
    ".nim": "nim",
}

_TEST_DIR_NAMES = frozenset({"test", "tests", "__tests__", "spec", "specs", "e2e"})

_TEST_FILENAME_RES = (
    re.compile(r"^test_.*\.py$"),
    re.compile(r".*_test\.py$"),
    re.compile(r".*\.test\.tsx?$"),
    re.compile(r".*\.spec\.tsx?$"),
    re.compile(r".*Test\.java$"),
    re.compile(r".*_test\.go$"),
)

_GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "generated by",
    "code generated by",
    "auto-generated",
)

# util/common/helper 等の「総称語のみ」で構成されたファイル名を検出するための語彙。
# 語彙自体に具体的なドメイン名 (User, Order 等) が 1 トークンでも混じれば False になる。
_VAGUE_TOKENS = frozenset(
    {
        "util",
        "utils",
        "helper",
        "helpers",
        "common",
        "misc",
        "service",
        "services",
        "manager",
        "managers",
        "base",
        "core",
        "shared",
        "general",
        "stuff",
    }
)

_CAMEL_BOUNDARY_RE = re.compile(r"(?<=[a-z0-9])(?=[A-Z])")
_TOKEN_SPLIT_RE = re.compile(r"[_\-.]+")


def detect_language(path: Path) -> str:
    return EXTENSION_LANGUAGE.get(path.suffix.lower(), "generic")


def is_code_path(path: Path) -> bool:
    """拡張子が ``EXTENSION_LANGUAGE`` に登録されているか (判定対象 allowlist)。

    未登録の拡張子と拡張子なしのファイルは False。後者には shebang 付きの
    スクリプトが含まれるが、内容を読む前の名前だけの判定に閉じている
    (shebang 判定は別途の課題)。
    """
    return path.suffix.lower() in EXTENSION_LANGUAGE


def is_test_path(path: Path) -> bool:
    dir_parts = {part.lower() for part in path.parts[:-1]}
    if dir_parts & _TEST_DIR_NAMES:
        return True
    return any(pattern.match(path.name) for pattern in _TEST_FILENAME_RES)


def is_generated_by_content(lines: list[str]) -> bool:
    """先頭 5 行 (呼び出し側が既にスライス済み想定) に generated マーカーを含むか。"""
    for line in lines[:5]:
        lowered = line.lower()
        if any(marker in lowered for marker in _GENERATED_MARKERS):
            return True
    return False


def _tokenize_stem(stem: str) -> list[str]:
    tokens: list[str] = []
    for part in _TOKEN_SPLIT_RE.split(stem):
        if not part:
            continue
        for sub in _CAMEL_BOUNDARY_RE.split(part):
            if sub:
                tokens.append(sub.lower())
    return tokens


def is_vague_filename(path: Path) -> bool:
    """stem の全トークンが総称語彙の部分集合なら True (例: utils.py, CommonService.ts)。

    1 トークンでも具体的なドメイン名を含めば False (例: user_service.py, UserService.ts)。
    """
    tokens = _tokenize_stem(path.stem)
    if not tokens:
        return False
    return all(token in _VAGUE_TOKENS for token in tokens)
