#!/usr/bin/env python3
"""純粋関数: 言語判定・test 判定・generated 判定・vague filename 判定。

ファイルシステムアクセスは行わない (source.py の責務)。
"""
from __future__ import annotations

import re
from pathlib import Path

# 判定対象の allowlist を兼ねる: ここに無い拡張子は `is_code_path` が False を
# 返し、__main__ が早期 skip する (0.2.0 以降)。Markdown / JSON / YAML / CSV /
# SQL 等の非コードファイルが行数だけで分割検討を促されるのを避けるため。
EXTENSION_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "javascriptreact",
    ".ts": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".tsx": "typescriptreact",
    ".java": "java",
    ".cs": "csharp",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".dart": "dart",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".php": "php",
    # 以下は 0.2.0 で追加。allowlist 化する前は "generic" (係数 1.0) として
    # 判定されていた実コードであり、登録しないと判定対象から丸ごと外れる。
    ".swift": "swift",
    ".c": "c",
    ".h": "c",
    ".cc": "cpp",
    ".cpp": "cpp",
    ".cxx": "cpp",
    ".hh": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".m": "objectivec",
    ".mm": "objectivec",
    ".scala": "scala",
    ".ex": "elixir",
    ".exs": "elixir",
    ".sh": "shell",
    ".bash": "shell",
    ".zsh": "shell",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".r": "r",
    ".vue": "vue",
    ".svelte": "svelte",
    ".groovy": "groovy",
    ".ps1": "powershell",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".hs": "haskell",
    ".erl": "erlang",
    ".jl": "julia",
    ".zig": "zig",
    ".nim": "nim",
}

_TEST_DIR_NAMES = frozenset({"test", "tests", "__tests__", "spec", "specs", "e2e"})

# test 判定に使うファイル名パターン。role が `test` になると閾値が 1.6 倍に
# 緩み `def_count` シグナルの評価対象から外れるため、拾い漏れは「テスト
# ファイルに通常ファイルの厳しさを当てる」誤発火として現れる。
#
# 大文字小文字は区別する (``Tests?\.`` 等)。区別しないと ``Latest.cs`` /
# ``Manifest.kt`` のような普通のファイル名まで test 扱いになる。
_TEST_FILENAME_RES = (
    # Python: test_foo.py / foo_test.py / conftest.py (完全一致。前方一致に
    # すると conftest_helpers.py のような通常ファイルまで巻き込む)
    re.compile(r"^test_.*\.py$"),
    re.compile(r".*_test\.py$"),
    re.compile(r"^conftest\.py$"),
    # JS/TS 系: foo.test.js / foo.spec.mjs / foo.test.tsx / foo.spec.cts ...
    re.compile(r".*\.(test|spec)\.(m?js|cjs|jsx|ts|mts|cts|tsx)$"),
    # Ruby: user_spec.rb (RSpec) / user_test.rb (minitest)
    re.compile(r".*_(spec|test)\.rb$"),
    # JVM/.NET/PHP/Swift/Scala: FooTest.java / FooTests.cs / FooTest.kt ...
    re.compile(r".*Tests?\.(java|cs|kt|kts|php|swift|scala|groovy)$"),
    # 接尾辞 _test を使う言語: foo_test.go / foo_test.dart / foo_test.rs ...
    re.compile(r".*_test\.(go|dart|rs|php|exs|ex)$"),
)

# 内容マーカーの走査行数。5 行では、ライセンスヘッダ (10〜15 行) の後に
# 生成物注記を置く実在の生成器 (OpenAPI Generator 等) や、Alembic の
# マイグレーション冒頭 docstring を取りこぼしていた。呼び出し側が渡す
# スライス幅もこの定数に揃える (片方だけ広げても効かない)。
GENERATED_MARKER_SCAN_LINES = 20

_GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "generated by",
    "code generated by",
    "auto-generated",
    # 0.4.0 追加。"generated by" に一致しない実在の言い回し。
    "auto generated",
    "automatically generated",
    "generated file",
    # Alembic のマイグレーションが冒頭 docstring に必ず持つ識別子。
    # ディレクトリ名 (migrations / versions) より狭く、手書きの
    # `alembic/env.py` のような同居ファイルを巻き込まない。
    "revision id:",
)

# util/common/helper 等の「総称語のみ」で構成されたファイル名を検出するための語彙。
# 語彙自体に具体的なドメイン名 (User, Order 等) が 1 トークンでも混じれば False になる。
_VAGUE_TOKENS = frozenset(
    {
        "util",
        "utils",
        "helper",
        "helpers",
        "common",
        "misc",
        "service",
        "services",
        "manager",
        "managers",
        "base",
        "core",
        "shared",
        "general",
        "stuff",
    }
)

_CAMEL_BOUNDARY_RE = re.compile(r"(?<=[a-z0-9])(?=[A-Z])")
_TOKEN_SPLIT_RE = re.compile(r"[_\-.]+")


def detect_language(path: Path) -> str:
    return EXTENSION_LANGUAGE.get(path.suffix.lower(), "generic")


def is_code_path(path: Path) -> bool:
    """拡張子が ``EXTENSION_LANGUAGE`` に登録されているか (判定対象 allowlist)。

    未登録の拡張子と拡張子なしのファイルは False。後者には shebang 付きの
    スクリプトが含まれるが、内容を読む前の名前だけの判定に閉じている
    (shebang 判定は別途の課題)。
    """
    return path.suffix.lower() in EXTENSION_LANGUAGE


def relevant_dir_parts(path: Path, cwd: str = "") -> tuple[str, ...]:
    """ディレクトリ名ベースの判定で見るべき祖先ディレクトリ名を返す。

    ``cwd`` が与えられ ``path`` がその内側にあるときは、**``cwd`` からの相対
    ディレクトリのみ**を返す。全祖先を見ると、プロジェクトの外にあるだけの
    ディレクトリ名が判定に混入する — 例えば ``cwd`` が
    ``/home/alice/test/project`` のとき、その配下の ``src/main.py`` は
    ``test`` を祖先に持つため全祖先方式では test 扱いになっていた。

    ``cwd`` が空、または ``path`` が ``cwd`` の外にあって相対化できないときは
    全 parts を返す (従来の挙動)。フォールバック方向を「従来と同じ」に倒して
    いるのは、相対化の失敗 (macOS の ``/tmp`` symlink による表記揺れ等) で
    判定が静かに変わらないようにするため。``language.py`` は純粋関数の層
    なので realpath 正規化 (ファイルシステムアクセス) は行わない。
    """
    if cwd:
        try:
            return path.relative_to(cwd).parts[:-1]
        except (TypeError, ValueError):
            pass
    return path.parts[:-1]


def is_test_path(path: Path, cwd: str = "") -> bool:
    """テストファイルか (ディレクトリ名 または ファイル名パターン)。

    ``cwd`` は任意。与えるとディレクトリ名判定を ``cwd`` からの相対部分に
    限定する (``relevant_dir_parts`` 参照)。
    """
    dir_parts = {part.lower() for part in relevant_dir_parts(path, cwd)}
    if dir_parts & _TEST_DIR_NAMES:
        return True
    return any(pattern.match(path.name) for pattern in _TEST_FILENAME_RES)


def is_generated_by_content(lines: list[str]) -> bool:
    """先頭 ``GENERATED_MARKER_SCAN_LINES`` 行に generated マーカーを含むか。

    呼び出し側が既に同じ幅でスライス済みである想定だが、二重防御として
    ここでも絞る。
    """
    for line in lines[:GENERATED_MARKER_SCAN_LINES]:
        lowered = line.lower()
        if any(marker in lowered for marker in _GENERATED_MARKERS):
            return True
    return False


def _tokenize_stem(stem: str) -> list[str]:
    tokens: list[str] = []
    for part in _TOKEN_SPLIT_RE.split(stem):
        if not part:
            continue
        for sub in _CAMEL_BOUNDARY_RE.split(part):
            if sub:
                tokens.append(sub.lower())
    return tokens


def is_vague_filename(path: Path) -> bool:
    """stem の全トークンが総称語彙の部分集合なら True (例: utils.py, CommonService.ts)。

    1 トークンでも具体的なドメイン名を含めば False (例: user_service.py, UserService.ts)。
    """
    tokens = _tokenize_stem(path.stem)
    if not tokens:
        return False
    return all(token in _VAGUE_TOKENS for token in tokens)
